<?php 
	include('blocks/header/head.php');
	include('blocks/header/topbar-02.php');
	include('blocks/header/layout-02.php');
	include('blocks/ads/ads_970x90.php');
	include('blocks/newsticker/newsticker-02.php');
	include('blocks/sliders/layout-02.php');
	include('blocks/layouts/layout-02.php');
	include('blocks/header/search-modal.php');
	include('blocks/footer/footer-layout-02.php');
	include('blocks/footer/foot.php');
?>