<?php 
	include('blocks/header/head.php');
	include('blocks/header/topbar-01.php');
	include('blocks/header/layout-01.php');
	include('blocks/ads/ads_970x90.php');
	include('blocks/newsticker/newsticker.php');
	include('blocks/sliders/layout-01.php');
	include('blocks/layouts/layout-01.php');
	include('blocks/header/search-modal.php');
	include('blocks/footer/footer-layout-01.php');
	include('blocks/footer/foot.php');
?>